export interface SmallDealCard {
  id: number;
  type: 'SmallDeal';
  subtype: 'Income' | 'Growth' | 'Speculative' | 'Stable';
  category: 'stock' | 'realestate' | 'cd' | 'business' | 'collectibles';
  tags: string[];
  businessLevel?: 'small' | 'growth' | 'chain';
  industryTags?: string[];
  riskProfile?: 'low' | 'medium' | 'high';
  name: string;
  description: string;
  totalCost: number;
  downPayment: number;
  monthlyIncome: number;
  stockData?: {
    sharePrice: number;
    shares: number;
    priceRange: { min: number; max: number };
  };
}

export interface BigDealCard {
  id: number;
  type: 'BigDeal';
  subtype: 'Income' | 'Growth' | 'Speculative' | 'Stable';
  category: 'realestate' | 'business' | 'land';
  tags: string[];
  businessLevel?: 'small' | 'growth' | 'chain';
  industryTags?: string[];
  riskProfile?: 'low' | 'medium' | 'high';
  name: string;
  description: string;
  totalCost: number;
  downPayment: number;
  monthlyIncome: number;
}

export interface DoodadCard {
  id: number;
  type: 'Doodad';
  name: string;
  description: string;
  cost: number;
}

export const smallDealCards: SmallDealCard[] = [
  {
    id: 1,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'realestate',
    tags: ['apartment', 'realestate', '公寓', '房产'],
    name: '两室一厅公寓',
    description: '一套位置不错的两室一厅公寓出租机会',
    totalCost: 5000,
    downPayment: 2000,
    monthlyIncome: 200,
  },
  {
    id: 2,
    type: 'SmallDeal',
    subtype: 'Speculative',
    category: 'stock',
    tags: ['Stock', 'stock', 'MYT4U', '股票'],
    name: '科技股 MYT4U',
    description: '一家新兴科技公司的股票',
    totalCost: 1000,
    downPayment: 1000,
    monthlyIncome: 50,
    stockData: {
      sharePrice: 10,
      shares: 100,
      priceRange: { min: 5, max: 30 },
    },
  },
  {
    id: 3,
    type: 'SmallDeal',
    subtype: 'Stable',
    category: 'cd',
    tags: ['cd', 'bank', '存单'],
    name: '银行存单',
    description: '5年期定期存单，稳定收益',
    totalCost: 3000,
    downPayment: 3000,
    monthlyIncome: 100,
  },
  {
    id: 4,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'vending', '企业'],
    name: '自动售货机',
    description: '办公楼内的自动售货机经营权',
    totalCost: 3000,
    downPayment: 1500,
    monthlyIncome: 150,
  },
  {
    id: 5,
    type: 'SmallDeal',
    subtype: 'Speculative',
    category: 'stock',
    tags: ['Stock', 'stock', 'OK4U', '股票'],
    name: '零售股 OK4U',
    description: '稳定的零售连锁店股票',
    totalCost: 800,
    downPayment: 800,
    monthlyIncome: 40,
    stockData: {
      sharePrice: 8,
      shares: 100,
      priceRange: { min: 5, max: 20 },
    },
  },
  {
    id: 6,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'realestate',
    tags: ['realestate', 'parking', '房产', '停车场'],
    name: '小型停车场',
    description: '市中心附近的小型停车场投资',
    totalCost: 4800,
    downPayment: 2400,
    monthlyIncome: 240,
  },
  {
    id: 101,
    type: 'SmallDeal',
    subtype: 'Speculative',
    category: 'stock',
    tags: ['Stock', 'stock', 'MYJT', '医药股', '股票'],
    name: '医药巨头股票 (MYJT)',
    description: '股价波动大，无月收益，等待新药获批暴涨。',
    totalCost: 10,
    downPayment: 10,
    monthlyIncome: 0,
  },
  {
    id: 102,
    type: 'SmallDeal',
    subtype: 'Growth',
    category: 'realestate',
    tags: ['realestate', 'Growth', '待拆迁', '旧房', '房产'],
    name: '城郊待拆迁旧房',
    description: '虽有维护费支出，但拆迁潜力大。',
    totalCost: 15000,
    downPayment: 3000,
    monthlyIncome: -50,
  },
  {
    id: 103,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', '洗衣房', '自动化'],
    name: '无人洗衣房',
    description: '稳定的自动化现金流收入。',
    totalCost: 20000,
    downPayment: 5000,
    monthlyIncome: 600,
  },
  {
    id: 104,
    type: 'SmallDeal',
    subtype: 'Speculative',
    category: 'collectibles',
    tags: ['Collectibles', 'collectibles', '收藏品', '限量'],
    name: '限量版收藏品',
    description: '占用现金，等待特定买家出现。',
    totalCost: 1000,
    downPayment: 1000,
    monthlyIncome: 0,
  },
  {
    id: 201,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'food', 'local_service', 'low_cost', '早餐档', '社区服务'],
    businessLevel: 'small',
    industryTags: ['food', 'local_service', 'low_cost'],
    riskProfile: 'low',
    name: '社区早餐档',
    description: '小区门口的早餐档，客流稳定，适合前期积累现金流。',
    totalCost: 6000,
    downPayment: 2000,
    monthlyIncome: 300,
  },
  {
    id: 202,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'vending', 'automation', 'low_labor', '无人售卖'],
    businessLevel: 'small',
    industryTags: ['vending', 'automation', 'low_labor'],
    riskProfile: 'low',
    name: '无人售卖柜',
    description: '写字楼里的无人售卖柜，人工成本低，但需要定期维护设备。',
    totalCost: 8000,
    downPayment: 3000,
    monthlyIncome: 420,
  },
  {
    id: 203,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'electronics', 'resale', '二手回收', '消费降级'],
    businessLevel: 'small',
    industryTags: ['electronics', 'resale'],
    riskProfile: 'medium',
    name: '二手手机回收摊',
    description: '回收和翻新二手手机，行情好时周转很快。',
    totalCost: 10000,
    downPayment: 3500,
    monthlyIncome: 500,
  },
  {
    id: 204,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'ecommerce', 'community', 'logistics', '团购'],
    businessLevel: 'small',
    industryTags: ['ecommerce', 'community', 'logistics'],
    riskProfile: 'medium',
    name: '小区团购站',
    description: '社区团购提货点，旺季订单多，但物流费用会影响利润。',
    totalCost: 12000,
    downPayment: 4000,
    monthlyIncome: 650,
  },
  {
    id: 205,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'pet', 'service', 'local_service', '宠物'],
    businessLevel: 'growth',
    industryTags: ['pet', 'service', 'local_service'],
    riskProfile: 'medium',
    name: '宠物洗护店',
    description: '社区宠物洗护店，客单价不错，但比较依赖员工服务质量。',
    totalCost: 18000,
    downPayment: 6000,
    monthlyIncome: 900,
  },
  {
    id: 206,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'laundry', 'automation', 'chainable', '洗衣房'],
    businessLevel: 'growth',
    industryTags: ['laundry', 'automation', 'chainable'],
    riskProfile: 'low',
    name: '自助洗衣房二店',
    description: '第二家自助洗衣房，自动化程度高，适合做连锁雏形。',
    totalCost: 24000,
    downPayment: 7000,
    monthlyIncome: 1050,
  },
  {
    id: 207,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'homestay', 'travel', 'realestate_service', '民宿'],
    businessLevel: 'growth',
    industryTags: ['homestay', 'travel', 'realestate_service'],
    riskProfile: 'medium',
    name: '民宿托管房源',
    description: '替房东运营民宿房源，旅游旺季收益高，也受监管影响。',
    totalCost: 30000,
    downPayment: 8000,
    monthlyIncome: 1200,
  },
  {
    id: 208,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'marketing', 'creator', 'online', '小红书'],
    businessLevel: 'growth',
    industryTags: ['marketing', 'creator', 'online'],
    riskProfile: 'medium',
    name: '小红书代运营工作室',
    description: '为本地品牌做内容种草和账号运营，平台规则变化会影响接单。',
    totalCost: 20000,
    downPayment: 5000,
    monthlyIncome: 950,
  },
  {
    id: 209,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'ai', 'digital_product', 'scalable', '设计模板'],
    businessLevel: 'growth',
    industryTags: ['ai', 'digital_product', 'scalable'],
    riskProfile: 'medium',
    name: 'AI 设计模板店',
    description: '售卖 AI 生成的设计模板，边际成本低，但有版权争议风险。',
    totalCost: 16000,
    downPayment: 4000,
    monthlyIncome: 800,
  },
  {
    id: 210,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'education', 'local_service', 'regulated', '托管班'],
    businessLevel: 'growth',
    industryTags: ['education', 'local_service', 'regulated'],
    riskProfile: 'high',
    name: '社区儿童托管班',
    description: '社区儿童托管服务，需求稳定，但对合规和口碑要求高。',
    totalCost: 28000,
    downPayment: 9000,
    monthlyIncome: 1300,
  },
  {
    id: 211,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'food', 'delivery', 'high_risk', '轻食'],
    businessLevel: 'growth',
    industryTags: ['food', 'delivery', 'high_risk'],
    riskProfile: 'high',
    name: '外卖轻食厨房',
    description: '主打健康餐的外卖厨房，订单增长快，也受平台抽佣影响。',
    totalCost: 25000,
    downPayment: 7500,
    monthlyIncome: 1100,
  },
  {
    id: 212,
    type: 'SmallDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'fitness', 'service', 'subscription', '私教'],
    businessLevel: 'growth',
    industryTags: ['fitness', 'service', 'subscription'],
    riskProfile: 'medium',
    name: '小型健身私教工作室',
    description: '用会员订阅支撑现金流，健康消费热时增长明显。',
    totalCost: 35000,
    downPayment: 10000,
    monthlyIncome: 1600,
  },
];

export const bigDealCards: BigDealCard[] = [
  {
    id: 1,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'realestate',
    tags: ['apartment', 'realestate', '公寓', '房产'],
    name: '8户公寓楼',
    description: '优质地段的8户公寓楼，租金稳定',
    totalCost: 50000,
    downPayment: 10000,
    monthlyIncome: 1200,
  },
  {
    id: 2,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'mall', '企业', '商业'],
    name: '购物中心',
    description: '繁华商圈的购物中心投资',
    totalCost: 100000,
    downPayment: 20000,
    monthlyIncome: 3500,
  },
  {
    id: 3,
    type: 'BigDeal',
    subtype: 'Growth',
    category: 'land',
    tags: ['land', '土地'],
    name: '20英亩土地',
    description: '郊区开发用地，长期投资',
    totalCost: 80000,
    downPayment: 16000,
    monthlyIncome: 1500,
  },
  {
    id: 4,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'realestate',
    tags: ['realestate', 'townhouse', '房产', '别墅'],
    name: '12户联排别墅',
    description: '高端社区的联排别墅项目',
    totalCost: 120000,
    downPayment: 24000,
    monthlyIncome: 4800,
  },
  {
    id: 5,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'company', '企业', '公司'],
    name: '大型公司收购',
    description: '收购一家成熟的制造业公司',
    totalCost: 150000,
    downPayment: 30000,
    monthlyIncome: 6000,
  },
  {
    id: 6,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'realestate',
    tags: ['realestate', 'office', '房产', '写字楼'],
    name: '写字楼投资',
    description: 'CBD核心区写字楼整层投资',
    totalCost: 200000,
    downPayment: 40000,
    monthlyIncome: 8000,
  },
  {
    id: 101,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'coffee', 'chain', 'food', '连锁咖啡'],
    businessLevel: 'chain',
    industryTags: ['coffee', 'chain', 'food'],
    riskProfile: 'medium',
    name: '三店连锁咖啡品牌',
    description: '已有三家门店的小型咖啡品牌，适合继续做区域扩张。',
    totalCost: 180000,
    downPayment: 45000,
    monthlyIncome: 6500,
  },
  {
    id: 102,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'homestay', 'travel', 'management', '民宿管理'],
    businessLevel: 'chain',
    industryTags: ['homestay', 'travel', 'management'],
    riskProfile: 'medium',
    name: '城市民宿管理公司',
    description: '管理多套城市民宿房源，旺季现金流强，监管变化也会放大影响。',
    totalCost: 220000,
    downPayment: 55000,
    monthlyIncome: 7800,
  },
  {
    id: 103,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'local_service', 'platform', 'scalable', '本地生活'],
    businessLevel: 'chain',
    industryTags: ['local_service', 'platform', 'scalable'],
    riskProfile: 'high',
    name: '本地生活服务平台',
    description: '连接社区维修、清洁和上门服务的平台型生意，增长快但运营复杂。',
    totalCost: 260000,
    downPayment: 65000,
    monthlyIncome: 9000,
  },
  {
    id: 104,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'ai', 'education', 'b2b', '企业培训'],
    businessLevel: 'chain',
    industryTags: ['ai', 'education', 'b2b'],
    riskProfile: 'medium',
    name: '企业 AI 培训公司',
    description: '为企业客户提供 AI 工具培训和流程咨询，受技术热度影响明显。',
    totalCost: 200000,
    downPayment: 50000,
    monthlyIncome: 7200,
  },
  {
    id: 105,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'pet', 'chain', 'service', '宠物服务'],
    businessLevel: 'chain',
    industryTags: ['pet', 'chain', 'service'],
    riskProfile: 'medium',
    name: '连锁宠物服务中心',
    description: '覆盖洗护、寄养和宠物用品的连锁服务中心。',
    totalCost: 240000,
    downPayment: 60000,
    monthlyIncome: 8400,
  },
  {
    id: 106,
    type: 'BigDeal',
    subtype: 'Income',
    category: 'business',
    tags: ['business', 'vending', 'automation', 'chain', '无人零售'],
    businessLevel: 'chain',
    industryTags: ['vending', 'automation', 'chain'],
    riskProfile: 'medium',
    name: '区域无人零售网络',
    description: '覆盖多个办公区的无人零售网络，自动化红利明显但设备维护压力大。',
    totalCost: 300000,
    downPayment: 75000,
    monthlyIncome: 10500,
  },
];

export const doodadCards: DoodadCard[] = [
  {
    id: 1,
    type: 'Doodad',
    name: '购买新手机',
    description: '最新款手机上市，你决定换一部',
    cost: 800,
  },
  {
    id: 2,
    type: 'Doodad',
    name: '家庭聚餐',
    description: '亲朋好友聚会，你请客',
    cost: 500,
  },
  {
    id: 3,
    type: 'Doodad',
    name: '名牌包包',
    description: '看中了一个心仪的名牌包',
    cost: 1200,
  },
  {
    id: 4,
    type: 'Doodad',
    name: '周末旅游',
    description: '计划了一次短途旅行',
    cost: 600,
  },
  {
    id: 5,
    type: 'Doodad',
    name: '汽车维修',
    description: '爱车需要进行大保养',
    cost: 900,
  },
  {
    id: 6,
    type: 'Doodad',
    name: '高尔夫会员',
    description: '购买高尔夫俱乐部年费会员',
    cost: 1500,
  },
];

export const getRandomSmallDealCard = (): SmallDealCard => {
  const randomIndex = Math.floor(Math.random() * smallDealCards.length);
  return smallDealCards[randomIndex];
};

export const getRandomBigDealCard = (): BigDealCard => {
  const randomIndex = Math.floor(Math.random() * bigDealCards.length);
  return bigDealCards[randomIndex];
};

export const getRandomDoodadCard = (): DoodadCard => {
  const randomIndex = Math.floor(Math.random() * doodadCards.length);
  return doodadCards[randomIndex];
};
